=== tgreyuk/fpldata.com/packages/backend/src/api/typings/schemas/entry-picks-response.schema.json
{"$schema":"http://json-schema.org/draft-07/schema#","type":"object","properties":{"activeChip":{"type":"null"},"automaticSubs":{"type":"array","items":{"type":"object","properties":{"entry":{"type":"integer"},"elementIn":{"type":"integer"},"elementOut":{"type":"integer"},"event":{"type":"integer"}}}},"entryHistory":{"type":"object","properties":{"event":{"type":"integer"},"points":{"type":"integer"},"totalPoints":{"type":"integer"},"rank":{"type":"integer"},"rankSort":{"type":"integer"},"overallRank":{"type":"integer"},"bank":{"type":"integer"},"value":{"type":"integer"},"eventTransfers":{"type":"integer"},"eventTransfersCost":{"type":"integer"},"pointsOnBench":{"type":"integer"}}},"picks":{"type":"array","items":{"type":"object","properties":{"element":{"type":"integer"},"position":{"type":"integer"},"multiplier":{"type":"integer"},"isCaptain":{"type":"boolean"},"isViceCaptain":{"type":"boolean"}}}}}}

=== tgreyuk/fpldata.com/packages/server/src/api/typings/fixtures/entry-picks-response.data.json
{"activeChip":null,"automaticSubs":[{"entry":3514308,"elementIn":358,"elementOut":218,"event":1},{"entry":3514308,"elementIn":271,"elementOut":421,"event":1}],"entryHistory":{"event":1,"points":54,"totalPoints":54,"rank":4077200,"rankSort":4140672,"overallRank":4077293,"bank":0,"value":1000,"eventTransfers":0,"eventTransfersCost":0,"pointsOnBench":8},"picks":[{"element":366,"position":1,"multiplier":1,"isCaptain":false,"isViceCaptain":false},{"element":183,"position":2,"multiplier":1,"isCaptain":false,"isViceCaptain":false},{"element":181,"position":3,"multiplier":1,"isCaptain":false,"isViceCaptain":false},{"element":337,"position":4,"multiplier":1,"isCaptain":false,"isViceCaptain":false},{"element":358,"position":5,"multiplier":1,"isCaptain":false,"isViceCaptain":false},{"element":345,"position":6,"multiplier":1,"isCaptain":false,"isViceCaptain":false},{"element":271,"position":7,"multiplier":1,"isCaptain":false,"isViceCaptain":false},{"element":191,"position":8,"multiplier":2,"isCaptain":true,"isViceCaptain":false},{"element":166,"position":9,"multiplier":1,"isCaptain":false,"isViceCaptain":true},{"element":67,"position":10,"multiplier":1,"isCaptain":false,"isViceCaptain":false},{"element":409,"position":11,"multiplier":1,"isCaptain":false,"isViceCaptain":false},{"element":93,"position":12,"multiplier":0,"isCaptain":false,"isViceCaptain":false},{"element":218,"position":13,"multiplier":0,"isCaptain":false,"isViceCaptain":false},{"element":421,"position":14,"multiplier":0,"isCaptain":false,"isViceCaptain":false},{"element":444,"position":15,"multiplier":0,"isCaptain":false,"isViceCaptain":false}]}
