=== tgreyuk/fpldata.com/packages/server/src/api/typings/schemas/entry.schema.json
{"$schema":"http://json-schema.org/draft-07/schema#","type":"object","properties":{"id":{"type":"integer"},"joinedTime":{"type":"string","format":"date-time"},"startedEvent":{"type":"integer"},"favouriteTeam":{"type":"null"},"playerFirstName":{"type":"string"},"playerLastName":{"type":"string"},"playerRegionId":{"type":"integer"},"playerRegionName":{"type":"string"},"playerRegionIsoCodeShort":{"type":"string"},"playerRegionIsoCodeLong":{"type":"string"},"summaryOverallPoints":{"type":"integer"},"summaryOverallRank":{"type":"integer"},"summaryEventPoints":{"type":"integer"},"summaryEventRank":{"type":"integer"},"currentEvent":{"type":"integer"},"leagues":{"type":"object","properties":{"classic":{"type":"array","items":{"type":"object","properties":{"id":{"type":"integer"},"name":{"type":"string"},"shortName":{"type":["string","null"]},"created":{"type":"string","format":"date-time"},"closed":{"type":"boolean"},"rank":{"type":"null"},"maxEntries":{"type":"null"},"leagueType":{"type":"string"},"scoring":{"type":"string"},"adminEntry":{"type":["null","integer"]},"startEvent":{"type":"integer"},"entryRank":{"type":"integer"},"entryLastRank":{"type":"integer"},"entryCanLeave":{"type":"boolean"},"entryCanAdmin":{"type":"boolean"},"entryCanInvite":{"type":"boolean"}}}},"h2h":{"type":"array","items":{}},"cup":{"type":"object","properties":{"matches":{"type":"array","items":{"type":"object","properties":{"id":{"type":"integer"},"entry1Entry":{"type":"integer"},"entry1Name":{"type":"string"},"entry1PlayerName":{"type":"string"},"entry1Points":{"type":"integer"},"entry1Win":{"type":"integer"},"entry1Draw":{"type":"integer"},"entry1Loss":{"type":"integer"},"entry1Total":{"type":"integer"},"entry2Entry":{"type":"integer"},"entry2Name":{"type":"string"},"entry2PlayerName":{"type":"string"},"entry2Points":{"type":"integer"},"entry2Win":{"type":"integer"},"entry2Draw":{"type":"integer"},"entry2Loss":{"type":"integer"},"entry2Total":{"type":"integer"},"isKnockout":{"type":"boolean"},"winner":{"type":"integer"},"seedValue":{"type":"null"},"event":{"type":"integer"},"tiebreak":{"type":"null"}}}},"status":{"type":"object","properties":{"qualificationEvent":{"type":"integer"},"qualificationNumbers":{"type":"integer"},"qualificationRank":{"type":"integer"},"qualificationState":{"type":"string"}}}}}}},"name":{"type":"string"},"kit":{"type":"null"},"lastDeadlineBank":{"type":"integer"},"lastDeadlineValue":{"type":"integer"},"lastDeadlineTotalTransfers":{"type":"integer"}}}

=== tgreyuk/fpldata.com/packages/backend/src/api/typings/fixtures/entry.data.json
{"id":3514308,"joinedTime":"2019-08-06T18:19:43.393907Z","startedEvent":1,"favouriteTeam":null,"playerFirstName":"Tom","playerLastName":"Grey","playerRegionId":241,"playerRegionName":"England","playerRegionIsoCodeShort":"EN","playerRegionIsoCodeLong":"ENG","summaryOverallPoints":2110,"summaryOverallRank":391269,"summaryEventPoints":56,"summaryEventRank":2948937,"currentEvent":46,"leagues":{"classic":[{"id":261,"name":"England","shortName":"region-241","created":"2019-06-25T11:25:48.920594Z","closed":false,"rank":null,"maxEntries":null,"leagueType":"s","scoring":"c","adminEntry":null,"startEvent":1,"entryRank":132944,"entryLastRank":122305,"entryCanLeave":false,"entryCanAdmin":false,"entryCanInvite":false},{"id":276,"name":"Gameweek 1","shortName":"event-1","created":"2019-06-25T11:25:49.137947Z","closed":false,"rank":null,"maxEntries":null,"leagueType":"s","scoring":"c","adminEntry":null,"startEvent":1,"entryRank":389954,"entryLastRank":359546,"entryCanLeave":false,"entryCanAdmin":false,"entryCanInvite":false},{"id":314,"name":"Overall","shortName":"overall","created":"2019-06-25T11:25:49.714514Z","closed":false,"rank":null,"maxEntries":null,"leagueType":"s","scoring":"c","adminEntry":null,"startEvent":1,"entryRank":391269,"entryLastRank":360625,"entryCanLeave":false,"entryCanAdmin":false,"entryCanInvite":false},{"id":12683,"name":"Fantasy Football Scout","shortName":null,"created":"2019-06-27T13:55:42.243382Z","closed":false,"rank":null,"maxEntries":null,"leagueType":"x","scoring":"c","adminEntry":44893,"startEvent":1,"entryRank":18912,"entryLastRank":17936,"entryCanLeave":true,"entryCanAdmin":false,"entryCanInvite":false},{"id":35235,"name":"Promotion  Issues","shortName":null,"created":"2019-06-28T07:20:14.645241Z","closed":false,"rank":null,"maxEntries":null,"leagueType":"x","scoring":"c","adminEntry":138714,"startEvent":1,"entryRank":4,"entryLastRank":3,"entryCanLeave":true,"entryCanAdmin":false,"entryCanInvite":false},{"id":619007,"name":"flatswans","shortName":null,"created":"2019-08-02T17:33:41.742753Z","closed":false,"rank":null,"maxEntries":null,"leagueType":"x","scoring":"c","adminEntry":2018046,"startEvent":1,"entryRank":2,"entryLastRank":2,"entryCanLeave":true,"entryCanAdmin":false,"entryCanInvite":false},{"id":847050,"name":"What's for lunch?","shortName":null,"created":"2019-08-06T18:20:38.506964Z","closed":false,"rank":null,"maxEntries":null,"leagueType":"x","scoring":"c","adminEntry":3514308,"startEvent":1,"entryRank":2,"entryLastRank":2,"entryCanLeave":false,"entryCanAdmin":true,"entryCanInvite":true}],"h2h":[],"cup":{"matches":[{"id":41944823,"entry1Entry":3514308,"entry1Name":"Happy Feet","entry1PlayerName":"Tom Grey","entry1Points":63,"entry1Win":0,"entry1Draw":0,"entry1Loss":0,"entry1Total":0,"entry2Entry":3013298,"entry2Name":"saif","entry2PlayerName":"Saif Hassan","entry2Points":79,"entry2Win":0,"entry2Draw":0,"entry2Loss":0,"entry2Total":0,"isKnockout":true,"winner":3013298,"seedValue":null,"event":17,"tiebreak":null}],"status":{"qualificationEvent":16,"qualificationNumbers":4194304,"qualificationRank":1370529,"qualificationState":"QUALIFIED"}}},"name":"Happy Feet","kit":null,"lastDeadlineBank":0,"lastDeadlineValue":1011,"lastDeadlineTotalTransfers":35}
