=== tgreyuk/fpldata.com/packages/server/src/api/typings/schemas/entry-transfers.schema.json
{"$schema":"http://json-schema.org/draft-07/schema#","type":"array","items":{"type":"object","properties":{"elementIn":{"type":"integer"},"elementInCost":{"type":"integer"},"elementOut":{"type":"integer"},"elementOutCost":{"type":"integer"},"entry":{"type":"integer"},"event":{"type":"integer"},"time":{"type":"string","format":"date-time"}}}}

=== tgreyuk/fpldata.com/packages/server/src/api/typings/fixtures/entry-transfers.data.json
[{"elementIn":211,"elementInCost":98,"elementOut":11,"elementOutCost":109,"entry":3514308,"event":46,"time":"2020-07-17T22:23:35.922865Z"},{"elementIn":302,"elementInCost":47,"elementOut":287,"elementOutCost":45,"entry":3514308,"event":46,"time":"2020-07-17T22:23:35.920957Z"},{"elementIn":295,"elementInCost":47,"elementOut":478,"elementOutCost":43,"entry":3514308,"event":46,"time":"2020-07-17T22:23:35.918790Z"},{"elementIn":84,"elementInCost":54,"elementOut":358,"elementOutCost":42,"entry":3514308,"event":46,"time":"2020-07-17T22:23:35.916749Z"},{"elementIn":660,"elementInCost":40,"elementOut":164,"elementOutCost":47,"entry":3514308,"event":46,"time":"2020-07-17T22:23:35.914510Z"},{"elementIn":211,"elementInCost":98,"elementOut":166,"elementOutCost":98,"entry":3514308,"event":45,"time":"2020-07-14T17:35:13.203503Z"},{"elementIn":113,"elementInCost":74,"elementOut":420,"elementOutCost":44,"entry":3514308,"event":45,"time":"2020-07-14T17:35:13.201394Z"},{"elementIn":297,"elementInCost":46,"elementOut":478,"elementOutCost":43,"entry":3514308,"event":45,"time":"2020-07-14T17:35:13.199333Z"},{"elementIn":549,"elementInCost":39,"elementOut":203,"elementOutCost":56,"entry":3514308,"event":45,"time":"2020-07-14T17:35:13.197182Z"},{"elementIn":308,"elementInCost":44,"elementOut":160,"elementOutCost":53,"entry":3514308,"event":45,"time":"2020-07-14T17:35:13.194454Z"},{"elementIn":166,"elementInCost":98,"elementOut":11,"elementOutCost":109,"entry":3514308,"event":45,"time":"2020-07-14T17:27:53.615613Z"},{"elementIn":431,"elementInCost":73,"elementOut":287,"elementOutCost":45,"entry":3514308,"event":45,"time":"2020-07-14T17:27:53.613794Z"},{"elementIn":214,"elementInCost":118,"elementOut":191,"elementOutCost":126,"entry":3514308,"event":45,"time":"2020-07-14T17:27:53.612195Z"},{"elementIn":203,"elementInCost":56,"elementOut":182,"elementOutCost":76,"entry":3514308,"event":45,"time":"2020-07-14T17:27:53.610286Z"},{"elementIn":105,"elementInCost":61,"elementOut":87,"elementOutCost":44,"entry":3514308,"event":45,"time":"2020-07-14T17:27:53.608336Z"},{"elementIn":341,"elementInCost":41,"elementOut":471,"elementOutCost":52,"entry":3514308,"event":45,"time":"2020-07-14T17:27:53.606107Z"},{"elementIn":87,"elementInCost":44,"elementOut":164,"elementOutCost":47,"entry":3514308,"event":45,"time":"2020-07-13T23:23:29.228331Z"},{"elementIn":160,"elementInCost":53,"elementOut":297,"elementOutCost":43,"entry":3514308,"event":43,"time":"2020-07-07T07:16:42.208232Z"},{"elementIn":234,"elementInCost":44,"elementOut":210,"elementOutCost":117,"entry":3514308,"event":42,"time":"2020-07-03T18:25:39.710416Z"},{"elementIn":191,"elementInCost":126,"elementOut":29,"elementOutCost":62,"entry":3514308,"event":42,"time":"2020-07-03T18:25:39.671745Z"},{"elementIn":11,"elementInCost":111,"elementOut":409,"elementOutCost":78,"entry":3514308,"event":39,"time":"2020-06-11T11:53:10.633269Z"},{"elementIn":210,"elementInCost":118,"elementOut":166,"elementOutCost":95,"entry":3514308,"event":39,"time":"2020-06-11T11:53:10.628919Z"},{"elementIn":215,"elementInCost":106,"elementOut":217,"elementOutCost":84,"entry":3514308,"event":39,"time":"2020-06-11T11:53:10.624861Z"},{"elementIn":29,"elementInCost":64,"elementOut":191,"elementOutCost":126,"entry":3514308,"event":39,"time":"2020-06-11T11:53:10.618080Z"},{"elementIn":358,"elementInCost":43,"elementOut":183,"elementOutCost":65,"entry":3514308,"event":39,"time":"2020-06-11T11:53:10.613966Z"},{"elementIn":471,"elementInCost":53,"elementOut":94,"elementOutCost":43,"entry":3514308,"event":39,"time":"2020-06-11T11:53:10.519791Z"},{"elementIn":287,"elementInCost":48,"elementOut":21,"elementOutCost":43,"entry":3514308,"event":30,"time":"2020-03-13T16:50:42.418649Z"},{"elementIn":217,"elementInCost":84,"elementOut":171,"elementOutCost":73,"entry":3514308,"event":29,"time":"2020-03-07T06:40:26.393318Z"},{"elementIn":618,"elementInCost":81,"elementOut":342,"elementOutCost":99,"entry":3514308,"event":27,"time":"2020-02-22T10:43:21.595380Z"},{"elementIn":342,"elementInCost":100,"elementOut":239,"elementOutCost":79,"entry":3514308,"event":26,"time":"2020-02-07T17:37:10.400739Z"},{"elementIn":420,"elementInCost":44,"elementOut":133,"elementOutCost":67,"entry":3514308,"event":26,"time":"2020-02-07T17:37:10.332108Z"},{"elementIn":191,"elementInCost":126,"elementOut":192,"elementOutCost":123,"entry":3514308,"event":25,"time":"2020-02-01T05:41:01.384482Z"},{"elementIn":239,"elementInCost":79,"elementOut":463,"elementOutCost":62,"entry":3514308,"event":24,"time":"2020-01-21T18:24:57.641524Z"},{"elementIn":313,"elementInCost":67,"elementOut":338,"elementOutCost":109,"entry":3514308,"event":22,"time":"2020-01-10T17:45:20.251782Z"},{"elementIn":182,"elementInCost":75,"elementOut":336,"elementOutCost":51,"entry":3514308,"event":22,"time":"2020-01-10T17:45:20.208182Z"},{"elementIn":338,"elementInCost":110,"elementOut":11,"elementOutCost":108,"entry":3514308,"event":20,"time":"2019-12-27T23:38:29.120671Z"},{"elementIn":336,"elementInCost":51,"elementOut":123,"elementOutCost":55,"entry":3514308,"event":20,"time":"2019-12-27T23:38:29.057369Z"},{"elementIn":192,"elementInCost":123,"elementOut":214,"elementOutCost":119,"entry":3514308,"event":16,"time":"2019-12-06T22:06:14.493451Z"},{"elementIn":409,"elementInCost":76,"elementOut":460,"elementOutCost":75,"entry":3514308,"event":14,"time":"2019-11-30T11:00:20.696282Z"},{"elementIn":133,"elementInCost":66,"elementOut":287,"elementOutCost":46,"entry":3514308,"event":14,"time":"2019-11-30T11:00:20.659339Z"},{"elementIn":478,"elementInCost":44,"elementOut":447,"elementOutCost":46,"entry":3514308,"event":13,"time":"2019-11-22T21:47:55.519215Z"},{"elementIn":183,"elementInCost":65,"elementOut":42,"elementOutCost":46,"entry":3514308,"event":11,"time":"2019-11-02T10:50:16.610502Z"},{"elementIn":166,"elementInCost":93,"elementOut":210,"elementOutCost":121,"entry":3514308,"event":11,"time":"2019-11-02T10:01:01.771269Z"},{"elementIn":11,"elementInCost":111,"elementOut":278,"elementOutCost":71,"entry":3514308,"event":9,"time":"2019-10-11T20:12:56.593939Z"},{"elementIn":171,"elementInCost":72,"elementOut":191,"elementOutCost":125,"entry":3514308,"event":9,"time":"2019-10-11T20:12:56.545573Z"},{"elementIn":21,"elementInCost":46,"elementOut":271,"elementOutCost":45,"entry":3514308,"event":8,"time":"2019-10-04T17:00:45.767844Z"},{"elementIn":278,"elementInCost":71,"elementOut":409,"elementOutCost":73,"entry":3514308,"event":7,"time":"2019-09-27T22:35:48.074507Z"},{"elementIn":210,"elementInCost":121,"elementOut":166,"elementOutCost":89,"entry":3514308,"event":5,"time":"2019-09-13T19:48:09.982459Z"},{"elementIn":463,"elementInCost":64,"elementOut":421,"elementOutCost":60,"entry":3514308,"event":5,"time":"2019-09-13T19:48:09.979974Z"},{"elementIn":287,"elementInCost":48,"elementOut":345,"elementOutCost":74,"entry":3514308,"event":5,"time":"2019-09-13T19:48:09.977903Z"},{"elementIn":42,"elementInCost":46,"elementOut":444,"elementOutCost":44,"entry":3514308,"event":5,"time":"2019-09-13T19:48:09.976047Z"},{"elementIn":164,"elementInCost":45,"elementOut":358,"elementOutCost":44,"entry":3514308,"event":5,"time":"2019-09-13T19:48:09.973535Z"},{"elementIn":123,"elementInCost":56,"elementOut":183,"elementOutCost":65,"entry":3514308,"event":5,"time":"2019-09-13T19:48:09.971589Z"},{"elementIn":94,"elementInCost":45,"elementOut":366,"elementOutCost":49,"entry":3514308,"event":5,"time":"2019-09-13T19:48:09.969509Z"},{"elementIn":460,"elementInCost":72,"elementOut":278,"elementOutCost":69,"entry":3514308,"event":5,"time":"2019-09-07T01:08:20.745540Z"},{"elementIn":447,"elementInCost":46,"elementOut":337,"elementOutCost":50,"entry":3514308,"event":5,"time":"2019-09-07T01:08:20.694536Z"},{"elementIn":278,"elementInCost":69,"elementOut":188,"elementOutCost":55,"entry":3514308,"event":4,"time":"2019-08-26T19:49:35.251720Z"},{"elementIn":297,"elementInCost":41,"elementOut":226,"elementOutCost":55,"entry":3514308,"event":4,"time":"2019-08-26T19:49:35.212056Z"},{"elementIn":188,"elementInCost":55,"elementOut":67,"elementOutCost":80,"entry":3514308,"event":2,"time":"2019-08-11T23:17:17.379568Z"},{"elementIn":214,"elementInCost":120,"elementOut":218,"elementOutCost":80,"entry":3514308,"event":2,"time":"2019-08-11T23:17:17.377440Z"},{"elementIn":226,"elementInCost":55,"elementOut":181,"elementOutCost":70,"entry":3514308,"event":2,"time":"2019-08-11T23:17:17.374951Z"}]
